spring.application.name=KafkaConsumer
spring.kafka.bootstrap-servers=172.27.183.130:9092,172.27.183.130:9093,172.27.183.130:9094

# Kafka Topic Configuration
app.kafka.topic=CallDataRecord

# Consumer Config
spring.kafka.consumer.group-id=item-consumers
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.enable-auto-commit=false

# Batch Configuration
spring.kafka.listener.type=batch
spring.kafka.consumer.max-poll-records=500
spring.kafka.listener.ack-mode=manual_immediate

# Database Configuration
spring.datasource.url=jdbc:postgresql://172.27.183.130:5432/kafka_db?currentSchema=billing
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=billing
spring.liquibase.liquibase-schema=billing

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
